Set-Alias -Name 'ctfs' -Value 'Connect-TfsTeamProjectCollection'
Set-Alias -Name 'ctp' -Value 'Connect-TfsTeamProjectCollection'
Set-Alias -Name 'ctfsp' -Value 'Connect-TfsTeamProjectCollection'
Set-Alias -Name 'itfs' -Value 'Invoke-TfsRestApi'
Set-Alias -Name 'Start-TfsBuild' -Value 'Start-TfsPipelineRun'
