using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Xsl;
using Microsoft.CodeAnalysis;

namespace TfsCmdlets.SourceGenerators
{
    public record ClassInfo
    {
        public ClassInfo(INamedTypeSymbol targetType,
            bool includeProperties = true,
            bool includeMethods = false,
            bool includeUsings = true,
            bool recurseMethods = false,
            string recurseMethodsStopAt = null)
        {
            if (targetType == null) throw new ArgumentNullException(nameof(targetType));

            Name = targetType.Name;
            Namespace = targetType.FullNamespace();
            FullName = targetType.FullName();
            FileName = $"{FullName}.g.cs";

            Methods = new EquatableArray<MethodInfo>(includeMethods
                ? GetMethods(targetType, recurseMethods, recurseMethodsStopAt).ToArray()
                : Array.Empty<MethodInfo>());

            Properties = new EquatableArray<PropertyInfo>(includeProperties
                ? GetProperties(targetType, recurseMethods, recurseMethodsStopAt).ToArray()
                : Array.Empty<PropertyInfo>());

            UsingsStatements = includeUsings
                ? targetType.GetUsingStatements()
                : string.Empty;

            CtorArgs = new EquatableArray<string>(GetCtorArgs(targetType).ToArray());
            ImportingConstructorArgs = GetImportingConstructorArguments(targetType);
            ImportingConstructorBody = GetImportingConstructorBody(targetType);

        }

        public ClassInfo(string name, string ns, string fullName, string fileName, IEnumerable<string> ctorArgs = null)
        {
            Name = name;
            Namespace = ns;
            FullName = fullName;
            FileName = fileName;
            CtorArgs = new EquatableArray<string>(ctorArgs?.ToArray() ?? Array.Empty<string>());
        }

        protected IEnumerable<MethodInfo> GetMethods(INamedTypeSymbol targetType, bool recursive = false, string? stopAt = null)
        {
            if (!recursive || (string.IsNullOrEmpty(stopAt)))
            {
                stopAt = targetType.FullName();
            }

            var methods = targetType
                .GetMembersRecursively(SymbolKind.Method, stopAt)
                .Cast<IMethodSymbol>()
                .Where(m =>
                    m.MethodKind == MethodKind.Ordinary &&
                    m.DeclaredAccessibility == Accessibility.Public &&
                    !m.IsStatic &&
                    !m.IsOverride &&
                    !m.HasAttribute("ObsoleteAttribute"));

            return methods.Select(m => new MethodInfo(m));
        }

        protected IEnumerable<PropertyInfo> GetProperties(INamedTypeSymbol targetType, bool recursive = false, string? stopAt = null)
        {
            if (!recursive || (string.IsNullOrEmpty(stopAt)))
            {
                stopAt = targetType.FullName();
            }

            var properties = targetType
                .GetMembersRecursively(SymbolKind.Property, stopAt)
                .Cast<IPropertySymbol>()
                .Where(p =>
                    !p.IsStatic &&
                    p.DeclaredAccessibility == Accessibility.Public)
                .ToList();

            return properties.Select(m => new PropertyInfo(m));
        }

        protected virtual IEnumerable<string> GetCtorArgs(INamedTypeSymbol symbol)
        {
            if (symbol.Constructors.Length == 0) return Array.Empty<string>();

            return symbol.Constructors[0]
                .Parameters
                .Select(p => $"{p.Type.Name} {p.Name}");
        }

        public string Name { get; set; }

        public string Namespace { get; }

        public string FullName { get; }

        public string FileName { get; }

        public EquatableArray<MethodInfo> Methods { get; set; }

        public EquatableArray<PropertyInfo> Properties { get; set; }

        public string UsingsStatements { get; set; }

        public EquatableArray<string> CtorArgs { get; set; }
        public string ImportingConstructorArgs { get; set;  }
        public string ImportingConstructorBody { get; }
        public string BaseClassName => Enumerable.Contains(BaseClassFullName, '.') ? Enumerable.Last<string>(BaseClassFullName.Split('.')) : BaseClassFullName;
        public string BaseClassFullName { get; set; }
        public string BaseClassImportingCtorArgs { get; set; }
        public string BaseClassImportingBaseArgs { get; set; }

        public override string ToString() => FullName;

        protected const string HEADER =
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the TfsCmdlets.SourceGenerators source generator
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            #nullable enable
            """;

        private const string BASE_CLASS_CTOR_ARGS = "IPowerShellService powerShell, IDataManager data, IParameterManager parameters, ILogger logger";
        private const string BASE_CLASS_BASE_ARGS = "powerShell, data, parameters, logger";

        public static ClassInfo CreateFromAttributeValue(GeneratorAttributeSyntaxContext ctx, string attributeName, string propertyName)
        {
            var node = ctx.TargetNode;
            var typeSymbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
            var targetType = typeSymbol?.GetAttributeNamedValue<INamedTypeSymbol>(attributeName, propertyName);

            return targetType is null 
                ? null 
                : new ClassInfo(targetType);
        }

        protected string GetImportingBaseArgs()
        {
            return BaseClassImportingBaseArgs ?? BASE_CLASS_BASE_ARGS;
        }

        protected string GetImportingConstructorBody(INamedTypeSymbol controller)
        {
            var parms = controller
                .GetPropertiesWithAttribute("ImportAttribute")
                .Select(p => $"            {p.Name} = {p.Name[0].ToString().ToLower()}{p.Name.Substring(1)};")
                .ToList();

            var client = controller.GetAttributeNamedValue<INamedTypeSymbol>("CmdletControllerAttribute", "Client");

            if (client != null) parms.Add($"            Client = client;");

            return string.Join("\n", parms);
        }

        protected string GetImportingConstructorArguments(INamedTypeSymbol controller)
        {
            var sb = new StringBuilder();
            var ctorArgs = controller.GetImportingConstructorArguments();

            if ((ctorArgs?.IndexOf(BASE_CLASS_CTOR_ARGS, StringComparison.Ordinal) ?? -1) >= 0)
            {
                return ctorArgs;
            }

            if (!string.IsNullOrEmpty(ctorArgs)) sb.Append($"{ctorArgs}, ");

            return sb
                .Append(BASE_CLASS_CTOR_ARGS)
                //.Append(string.IsNullOrEmpty(ctorArgs)
                //    ? string.Empty
                //    : $", {ctorArgs}")
                .ToString();
        }
    }
}