using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Xsl;
using Microsoft.CodeAnalysis;

namespace TfsCmdlets.SourceGenerators
{
    public record ClassInfo
    {
        public ClassInfo(INamedTypeSymbol targetType, 
            bool includeProperties = true, 
            bool includeMethods = false, 
            bool includeUsings = true,
            bool recurseMethods = false,
            string recurseMethodsStopAt = null)
        {
            if (targetType == null) throw new ArgumentNullException(nameof(targetType));

            Name = targetType.Name;
            Namespace = targetType.FullNamespace();
            FullName = targetType.FullName();
            FileName = $"{FullName}.g.cs";

            Methods = new EquatableArray<MethodInfo>(includeMethods
                ? GetMethods(targetType, recurseMethods, recurseMethodsStopAt).ToArray()
                : Array.Empty<MethodInfo>());

            Properties = new EquatableArray<PropertyInfo>(includeProperties
                ? GetProperties(targetType).ToArray()
                : Array.Empty<PropertyInfo>());

            UsingsStatements = includeUsings
                ? targetType.GetUsingStatements()
                : string.Empty;
        }

        protected IEnumerable<MethodInfo> GetMethods(INamedTypeSymbol targetType, bool recursive = false, string? stopAt = null)
        {
            if (!recursive || (string.IsNullOrEmpty(stopAt)))
            {
                stopAt = targetType.FullName();
            }

            var methods = targetType
                .GetMembersRecursively(SymbolKind.Method, stopAt)
                .Cast<IMethodSymbol>()
                .Where(m =>
                    m.MethodKind == MethodKind.Ordinary &&
                    m.DeclaredAccessibility == Accessibility.Public &&
                    !m.IsOverride &&
                    !m.HasAttribute("ObsoleteAttribute"));

            return methods.Select(m => new MethodInfo(m));
        }

        protected IEnumerable<PropertyInfo> GetProperties(INamedTypeSymbol targetType)
        {
            var props = targetType
                .GetMembers()
                .Where(m =>
                    m.Kind == SymbolKind.Property &&
                    m.DeclaredAccessibility == Accessibility.Public)
                .Cast<IPropertySymbol>();

            return props.Select(p => new PropertyInfo(p));
        }

        public string Name { get; }

        public string Namespace { get; }

        public string FullName { get; }

        public string FileName { get; }

        public EquatableArray<MethodInfo> Methods { get; }

        public EquatableArray<PropertyInfo> Properties { get; }
        
        public string UsingsStatements { get; }

        public override string ToString() => FullName;

        protected const string HEADER =
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the TfsCmdlets.SourceGenerators source generator
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            #nullable enable
            """;
    }
}