using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace TfsCmdlets.SourceGenerators
{
    public abstract record ClassInfoBase
    {
        public ClassInfoBase(INamedTypeSymbol targetType, bool includeProperties = false, bool includeMethods = false)
        {
            if (targetType == null) throw new ArgumentNullException(nameof(targetType));

            Name = targetType.Name;
            Namespace = targetType.FullNamespace();
            FullName = FileName = targetType.FullName();

            Methods = includeMethods? 
                new EquatableArray<MethodInfo>(GetMethods(targetType).ToArray()) :
                Methods = new EquatableArray<MethodInfo>(Array.Empty<MethodInfo>());

            Properties = includeProperties ?
                new EquatableArray<PropertyInfo>(GetProperties(targetType).ToArray()) :
                new EquatableArray<PropertyInfo>(Array.Empty<PropertyInfo>());
        }

        private IEnumerable<MethodInfo> GetMethods(INamedTypeSymbol targetType)
        {
            throw new NotImplementedException();
        }

        private IEnumerable<PropertyInfo> GetProperties(INamedTypeSymbol targetType)
        {
            throw new NotImplementedException();
        }

        public string Name { get; }

        public string Namespace { get; }

        public string FullName { get; }

        public string FileName { get; }

        public EquatableArray<MethodInfo> Methods { get; }

        public EquatableArray<PropertyInfo> Properties { get; }

        public virtual string GenerateCode() => string.Empty;

        protected const string HEADER =
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the TfsCmdlets.SourceGenerators source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable
        """;
    }
}
