using System;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;

namespace TfsCmdlets.SourceGenerators
{
    public abstract record GeneratorState
    {
        protected const string HEADER = 
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the TfsCmdlets.SourceGenerators source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable
        """;

        public GeneratorState(INamedTypeSymbol targetType)
        {
            if (targetType == null) throw new ArgumentNullException(nameof(targetType));

            Name = targetType.Name;
            Namespace = targetType.FullNamespace();
            FullName = FileName = targetType.FullName();
        }

        public string Name { get; }

        public string Namespace { get; }

        public string FullName { get; }

        public string FileName { get; }
        
        public EquatableArray<GeneratedProperty> GeneratedProperties { get; protected set; }

        public abstract string GenerateCode();
    }
}
