ViewSelectedBy: 
  - Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings
GroupBy: 
  ScriptBlock: $_.Project + '/' + $_.Team
  CustomControlName: TeamProjects-Teams
TableControl: 
  'Board name': 
    ScriptBlock: ([uri] $_.Links.Links.board.Href).Segments[-1]
  'Card Style Rules': 
    ScriptBlock: $_.rules['fill'].Name -join ', '
  'Tag Color Rules': 
    ScriptBlock: $_.rules['tagStyle'].Name -join ', '
