ViewSelectedBy: 
  - Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings
GroupBy: 
  ScriptBlock: $_.Project + '/' + $_.Team
  CustomControlName: TeamProjects-Teams
TableControl: 
  Board: 
  CardRules: 
    Label: "Card Rules"
    ScriptBlock: return "{$($_.CardRules.Name -join ', ')}"
  TagRules: 
    Label: "Tag Rules"
    ScriptBlock: return "{$($_.TagRules.Name -join ', ')}"