ViewSelectedBy:
  - Microsoft.TeamFoundation.Policy.WebApi.PolicyConfiguration
GroupBy: 
  ScriptBlock: $_.ProjectId + '/' + $_.RepositoryId + '/' + $_.RefName
  CustomControlName: TeamProjects-Repositories-Branches
TableControl: 
  DisplayName: 
    Label: Display Name
  Details:
    ScriptBlock: |
      $buildDef = $_.BuildDefinition
      switch ($_.DisplayName)
      {
        'Build' { 'Build Definition: ' + $buildDef }
        default { '' }
      }
      
  IsEnabled:
    Label: "Is Enabled?"