//HintName: TfsCmdlets.HttpClients.IWorkHttpClient.g.cs
#pragma warning disable CS8669
using System.Composition;
using Microsoft.TeamFoundation.Work.WebApi;
namespace TfsCmdlets.HttpClients
{
    public partial interface IWorkHttpClient: Microsoft.VisualStudio.Services.WebApi.IVssHttpClient
    {
		public System.Threading.Tasks.Task UpdateAutomationRuleAsync(Microsoft.TeamFoundation.Work.WebApi.Contracts.AutomationRules.TeamAutomationRulesSettingsRequestModel ruleRequestModel, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BacklogConfiguration> GetBacklogConfigurationsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BacklogLevelWorkItems> GetBacklogLevelWorkItemsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string backlogId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BacklogLevelConfiguration> GetBacklogAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BacklogLevelConfiguration>> GetBacklogsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadge> GetBoardBadgeAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid id, Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadgeColumnOptions? columnOptions = default(Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadgeColumnOptions?), System.Collections.Generic.IEnumerable<string> columns = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<string> GetBoardBadgeDataAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid id, Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadgeColumnOptions? columnOptions = default(Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadgeColumnOptions?), System.Collections.Generic.IEnumerable<string> columns = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetColumnSuggestedValuesAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetColumnSuggestedValuesAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetColumnSuggestedValuesAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.ParentChildWIMap>> GetBoardMappingParentItemsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string childBacklogContextCategoryRefName, System.Collections.Generic.IEnumerable<int> workitemIds, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetRowSuggestedValuesAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetRowSuggestedValuesAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetRowSuggestedValuesAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Board> GetBoardAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardReference>> GetBoardsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> SetBoardOptionsAsync(System.Collections.Generic.IDictionary<string, string> options, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardUserSettings> GetBoardUserSettingsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardUserSettings> UpdateBoardUserSettingsAsync(System.Collections.Generic.IDictionary<string, string> boardUserSettings, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamCapacity> GetCapacitiesWithIdentityRefAndTotalsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef> GetCapacityWithIdentityRefAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, System.Guid teamMemberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef>> ReplaceCapacitiesWithIdentityRefAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef> capacities, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef> UpdateCapacityWithIdentityRefAsync(Microsoft.TeamFoundation.Work.WebApi.CapacityPatch patch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, System.Guid teamMemberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings> GetBoardCardRuleSettingsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings> UpdateBoardCardRuleSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings boardCardRuleSettings, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task UpdateTaskboardCardRuleSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings boardCardRuleSettings, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardCardSettings> GetBoardCardSettingsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardCardSettings> UpdateBoardCardSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.BoardCardSettings boardCardSettingsToSave, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task UpdateTaskboardCardSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.BoardCardSettings boardCardSettingsToSave, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.StreamContent> GetBoardChartImageAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, string name, int? width = default(int?), int? height = default(int?), bool? showDetails = default(bool?), string title = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.StreamContent> GetIterationChartImageAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, string name, int? width = default(int?), int? height = default(int?), bool? showDetails = default(bool?), string title = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.StreamContent> GetIterationsChartImageAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string name, int? iterationsNumber = default(int?), int? width = default(int?), int? height = default(int?), bool? showDetails = default(bool?), string title = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardChart> GetBoardChartAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, string name, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardChartReference>> GetBoardChartsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardChart> UpdateBoardChartAsync(Microsoft.TeamFoundation.Work.WebApi.BoardChart chart, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, string name, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardColumn>> GetBoardColumnsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardColumn>> UpdateBoardColumnsAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.BoardColumn> boardColumns, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.DeliveryViewData> GetDeliveryTimelineDataAsync(string project, string id, int? revision = default(int?), System.DateTime? startDate = default(System.DateTime?), System.DateTime? endDate = default(System.DateTime?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.DeliveryViewData> GetDeliveryTimelineDataAsync(System.Guid project, string id, int? revision = default(int?), System.DateTime? startDate = default(System.DateTime?), System.DateTime? endDate = default(System.DateTime?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.IterationCapacity> GetTotalIterationCapacitiesAsync(string project, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.IterationCapacity> GetTotalIterationCapacitiesAsync(System.Guid project, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeleteTeamIterationAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsIteration> GetTeamIterationAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsIteration>> GetTeamIterationsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string timeframe = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsIteration> PostTeamIterationAsync(Microsoft.TeamFoundation.Work.WebApi.TeamSettingsIteration iteration, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> CreatePlanAsync(Microsoft.TeamFoundation.Work.WebApi.CreatePlan postedPlan, string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> CreatePlanAsync(Microsoft.TeamFoundation.Work.WebApi.CreatePlan postedPlan, System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeletePlanAsync(string project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeletePlanAsync(System.Guid project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> GetPlanAsync(string project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> GetPlanAsync(System.Guid project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.Plan>> GetPlansAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.Plan>> GetPlansAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> UpdatePlanAsync(Microsoft.TeamFoundation.Work.WebApi.UpdatePlan updatedPlan, string project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> UpdatePlanAsync(Microsoft.TeamFoundation.Work.WebApi.UpdatePlan updatedPlan, System.Guid project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.PredefinedQuery>> GetPredefinedQueriesAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.PredefinedQuery>> GetPredefinedQueriesAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.PredefinedQuery> GetPredefinedQueryResultsAsync(string project, string id, int? top = default(int?), bool? includeCompleted = default(bool?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.PredefinedQuery> GetPredefinedQueryResultsAsync(System.Guid project, string id, int? top = default(int?), bool? includeCompleted = default(bool?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.ProcessConfiguration> GetProcessConfigurationAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.ProcessConfiguration> GetProcessConfigurationAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardRow>> GetBoardRowsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardRow>> UpdateBoardRowsAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.BoardRow> boardRows, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.TaskboardColumns> GetColumnsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.TaskboardColumns> UpdateColumnsAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.UpdateTaskboardColumn> updateColumns, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.TaskboardWorkItemColumn>> GetWorkItemColumnsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task UpdateWorkItemColumnAsync(Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.UpdateTaskboardWorkItemColumn updateColumn, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, int workItemId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsDaysOff> GetTeamDaysOffAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsDaysOff> UpdateTeamDaysOffAsync(Microsoft.TeamFoundation.Work.WebApi.TeamSettingsDaysOffPatch daysOffPatch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamFieldValues> GetTeamFieldValuesAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamFieldValues> UpdateTeamFieldValuesAsync(Microsoft.TeamFoundation.Work.WebApi.TeamFieldValuesPatch patch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSetting> GetTeamSettingsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSetting> UpdateTeamSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.TeamSettingsPatch teamSettingsPatch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.IterationWorkItems> GetIterationWorkItemsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.ReorderResult>> ReorderBacklogWorkItemsAsync(Microsoft.TeamFoundation.Work.WebApi.ReorderOperation operation, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.ReorderResult>> ReorderIterationWorkItemsAsync(Microsoft.TeamFoundation.Work.WebApi.ReorderOperation operation, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity>> GetCapacitiesAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity> GetCapacityAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, System.Guid teamMemberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity>> ReplaceCapacitiesAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity> capacities, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity> UpdateCapacityAsync(Microsoft.TeamFoundation.Work.WebApi.CapacityPatch patch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, System.Guid teamMemberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef>> GetCapacitiesWithIdentityRefAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
    [Export(typeof(IWorkHttpClient))]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal class IWorkHttpClientImpl: IWorkHttpClient
    {
        private Microsoft.TeamFoundation.Work.WebApi.WorkHttpClient _client;
        protected IDataManager Data { get; }
        [ImportingConstructor]
        public IWorkHttpClientImpl(IDataManager data)
        {
            Data = data;
        }
        private Microsoft.TeamFoundation.Work.WebApi.WorkHttpClient Client
        {
            get
            {
                if(_client == null)
                {
                    _client = (Data.GetCollection() as TfsCmdlets.Services.ITfsServiceProvider)?.GetClient(typeof(Microsoft.TeamFoundation.Work.WebApi.WorkHttpClient)) as Microsoft.TeamFoundation.Work.WebApi.WorkHttpClient;
                }
                return _client;
            }
        }
		public System.Threading.Tasks.Task UpdateAutomationRuleAsync(Microsoft.TeamFoundation.Work.WebApi.Contracts.AutomationRules.TeamAutomationRulesSettingsRequestModel ruleRequestModel, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateAutomationRuleAsync(ruleRequestModel, teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BacklogConfiguration> GetBacklogConfigurationsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBacklogConfigurationsAsync(teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BacklogLevelWorkItems> GetBacklogLevelWorkItemsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string backlogId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBacklogLevelWorkItemsAsync(teamContext, backlogId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BacklogLevelConfiguration> GetBacklogAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBacklogAsync(teamContext, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BacklogLevelConfiguration>> GetBacklogsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBacklogsAsync(teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadge> GetBoardBadgeAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid id, Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadgeColumnOptions? columnOptions = default(Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadgeColumnOptions?), System.Collections.Generic.IEnumerable<string> columns = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardBadgeAsync(teamContext, id, columnOptions, columns, userState, cancellationToken);
		public System.Threading.Tasks.Task<string> GetBoardBadgeDataAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid id, Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadgeColumnOptions? columnOptions = default(Microsoft.TeamFoundation.Work.WebApi.Contracts.BoardBadgeColumnOptions?), System.Collections.Generic.IEnumerable<string> columns = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardBadgeDataAsync(teamContext, id, columnOptions, columns, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetColumnSuggestedValuesAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetColumnSuggestedValuesAsync(userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetColumnSuggestedValuesAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetColumnSuggestedValuesAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetColumnSuggestedValuesAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetColumnSuggestedValuesAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.ParentChildWIMap>> GetBoardMappingParentItemsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string childBacklogContextCategoryRefName, System.Collections.Generic.IEnumerable<int> workitemIds, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardMappingParentItemsAsync(teamContext, childBacklogContextCategoryRefName, workitemIds, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetRowSuggestedValuesAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetRowSuggestedValuesAsync(userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetRowSuggestedValuesAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetRowSuggestedValuesAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardSuggestedValue>> GetRowSuggestedValuesAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetRowSuggestedValuesAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Board> GetBoardAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardAsync(teamContext, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardReference>> GetBoardsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardsAsync(teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> SetBoardOptionsAsync(System.Collections.Generic.IDictionary<string, string> options, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.SetBoardOptionsAsync(options, teamContext, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardUserSettings> GetBoardUserSettingsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardUserSettingsAsync(teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardUserSettings> UpdateBoardUserSettingsAsync(System.Collections.Generic.IDictionary<string, string> boardUserSettings, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateBoardUserSettingsAsync(boardUserSettings, teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamCapacity> GetCapacitiesWithIdentityRefAndTotalsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetCapacitiesWithIdentityRefAndTotalsAsync(teamContext, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef> GetCapacityWithIdentityRefAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, System.Guid teamMemberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetCapacityWithIdentityRefAsync(teamContext, iterationId, teamMemberId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef>> ReplaceCapacitiesWithIdentityRefAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef> capacities, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReplaceCapacitiesWithIdentityRefAsync(capacities, teamContext, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef> UpdateCapacityWithIdentityRefAsync(Microsoft.TeamFoundation.Work.WebApi.CapacityPatch patch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, System.Guid teamMemberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateCapacityWithIdentityRefAsync(patch, teamContext, iterationId, teamMemberId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings> GetBoardCardRuleSettingsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardCardRuleSettingsAsync(teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings> UpdateBoardCardRuleSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings boardCardRuleSettings, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateBoardCardRuleSettingsAsync(boardCardRuleSettings, teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task UpdateTaskboardCardRuleSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.BoardCardRuleSettings boardCardRuleSettings, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateTaskboardCardRuleSettingsAsync(boardCardRuleSettings, teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardCardSettings> GetBoardCardSettingsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardCardSettingsAsync(teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardCardSettings> UpdateBoardCardSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.BoardCardSettings boardCardSettingsToSave, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateBoardCardSettingsAsync(boardCardSettingsToSave, teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task UpdateTaskboardCardSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.BoardCardSettings boardCardSettingsToSave, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateTaskboardCardSettingsAsync(boardCardSettingsToSave, teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.StreamContent> GetBoardChartImageAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, string name, int? width = default(int?), int? height = default(int?), bool? showDetails = default(bool?), string title = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardChartImageAsync(teamContext, board, name, width, height, showDetails, title, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.StreamContent> GetIterationChartImageAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, string name, int? width = default(int?), int? height = default(int?), bool? showDetails = default(bool?), string title = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetIterationChartImageAsync(teamContext, iterationId, name, width, height, showDetails, title, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.StreamContent> GetIterationsChartImageAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string name, int? iterationsNumber = default(int?), int? width = default(int?), int? height = default(int?), bool? showDetails = default(bool?), string title = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetIterationsChartImageAsync(teamContext, name, iterationsNumber, width, height, showDetails, title, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardChart> GetBoardChartAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, string name, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardChartAsync(teamContext, board, name, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardChartReference>> GetBoardChartsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardChartsAsync(teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.BoardChart> UpdateBoardChartAsync(Microsoft.TeamFoundation.Work.WebApi.BoardChart chart, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, string name, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateBoardChartAsync(chart, teamContext, board, name, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardColumn>> GetBoardColumnsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardColumnsAsync(teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardColumn>> UpdateBoardColumnsAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.BoardColumn> boardColumns, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateBoardColumnsAsync(boardColumns, teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.DeliveryViewData> GetDeliveryTimelineDataAsync(string project, string id, int? revision = default(int?), System.DateTime? startDate = default(System.DateTime?), System.DateTime? endDate = default(System.DateTime?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetDeliveryTimelineDataAsync(project, id, revision, startDate, endDate, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.DeliveryViewData> GetDeliveryTimelineDataAsync(System.Guid project, string id, int? revision = default(int?), System.DateTime? startDate = default(System.DateTime?), System.DateTime? endDate = default(System.DateTime?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetDeliveryTimelineDataAsync(project, id, revision, startDate, endDate, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.IterationCapacity> GetTotalIterationCapacitiesAsync(string project, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetTotalIterationCapacitiesAsync(project, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.IterationCapacity> GetTotalIterationCapacitiesAsync(System.Guid project, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetTotalIterationCapacitiesAsync(project, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task DeleteTeamIterationAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteTeamIterationAsync(teamContext, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsIteration> GetTeamIterationAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetTeamIterationAsync(teamContext, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsIteration>> GetTeamIterationsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string timeframe = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetTeamIterationsAsync(teamContext, timeframe, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsIteration> PostTeamIterationAsync(Microsoft.TeamFoundation.Work.WebApi.TeamSettingsIteration iteration, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.PostTeamIterationAsync(iteration, teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> CreatePlanAsync(Microsoft.TeamFoundation.Work.WebApi.CreatePlan postedPlan, string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreatePlanAsync(postedPlan, project, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> CreatePlanAsync(Microsoft.TeamFoundation.Work.WebApi.CreatePlan postedPlan, System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreatePlanAsync(postedPlan, project, userState, cancellationToken);
		public System.Threading.Tasks.Task DeletePlanAsync(string project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeletePlanAsync(project, id, userState, cancellationToken);
		public System.Threading.Tasks.Task DeletePlanAsync(System.Guid project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeletePlanAsync(project, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> GetPlanAsync(string project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetPlanAsync(project, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> GetPlanAsync(System.Guid project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetPlanAsync(project, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.Plan>> GetPlansAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetPlansAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.Plan>> GetPlansAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetPlansAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> UpdatePlanAsync(Microsoft.TeamFoundation.Work.WebApi.UpdatePlan updatedPlan, string project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdatePlanAsync(updatedPlan, project, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Plan> UpdatePlanAsync(Microsoft.TeamFoundation.Work.WebApi.UpdatePlan updatedPlan, System.Guid project, string id, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdatePlanAsync(updatedPlan, project, id, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.PredefinedQuery>> GetPredefinedQueriesAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetPredefinedQueriesAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.PredefinedQuery>> GetPredefinedQueriesAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetPredefinedQueriesAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.PredefinedQuery> GetPredefinedQueryResultsAsync(string project, string id, int? top = default(int?), bool? includeCompleted = default(bool?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetPredefinedQueryResultsAsync(project, id, top, includeCompleted, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.PredefinedQuery> GetPredefinedQueryResultsAsync(System.Guid project, string id, int? top = default(int?), bool? includeCompleted = default(bool?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetPredefinedQueryResultsAsync(project, id, top, includeCompleted, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.ProcessConfiguration> GetProcessConfigurationAsync(string project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetProcessConfigurationAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.ProcessConfiguration> GetProcessConfigurationAsync(System.Guid project, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetProcessConfigurationAsync(project, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardRow>> GetBoardRowsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBoardRowsAsync(teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.BoardRow>> UpdateBoardRowsAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.BoardRow> boardRows, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, string board, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateBoardRowsAsync(boardRows, teamContext, board, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.TaskboardColumns> GetColumnsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetColumnsAsync(teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.TaskboardColumns> UpdateColumnsAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.UpdateTaskboardColumn> updateColumns, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateColumnsAsync(updateColumns, teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.TaskboardWorkItemColumn>> GetWorkItemColumnsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetWorkItemColumnsAsync(teamContext, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task UpdateWorkItemColumnAsync(Microsoft.TeamFoundation.Work.WebApi.Contracts.Taskboard.UpdateTaskboardWorkItemColumn updateColumn, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, int workItemId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateWorkItemColumnAsync(updateColumn, teamContext, iterationId, workItemId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsDaysOff> GetTeamDaysOffAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetTeamDaysOffAsync(teamContext, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSettingsDaysOff> UpdateTeamDaysOffAsync(Microsoft.TeamFoundation.Work.WebApi.TeamSettingsDaysOffPatch daysOffPatch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateTeamDaysOffAsync(daysOffPatch, teamContext, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamFieldValues> GetTeamFieldValuesAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetTeamFieldValuesAsync(teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamFieldValues> UpdateTeamFieldValuesAsync(Microsoft.TeamFoundation.Work.WebApi.TeamFieldValuesPatch patch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateTeamFieldValuesAsync(patch, teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSetting> GetTeamSettingsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetTeamSettingsAsync(teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamSetting> UpdateTeamSettingsAsync(Microsoft.TeamFoundation.Work.WebApi.TeamSettingsPatch teamSettingsPatch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateTeamSettingsAsync(teamSettingsPatch, teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.IterationWorkItems> GetIterationWorkItemsAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetIterationWorkItemsAsync(teamContext, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.ReorderResult>> ReorderBacklogWorkItemsAsync(Microsoft.TeamFoundation.Work.WebApi.ReorderOperation operation, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReorderBacklogWorkItemsAsync(operation, teamContext, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.ReorderResult>> ReorderIterationWorkItemsAsync(Microsoft.TeamFoundation.Work.WebApi.ReorderOperation operation, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReorderIterationWorkItemsAsync(operation, teamContext, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity>> GetCapacitiesAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetCapacitiesAsync(teamContext, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity> GetCapacityAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, System.Guid teamMemberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetCapacityAsync(teamContext, iterationId, teamMemberId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity>> ReplaceCapacitiesAsync(System.Collections.Generic.IEnumerable<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity> capacities, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReplaceCapacitiesAsync(capacities, teamContext, iterationId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacity> UpdateCapacityAsync(Microsoft.TeamFoundation.Work.WebApi.CapacityPatch patch, Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, System.Guid teamMemberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateCapacityAsync(patch, teamContext, iterationId, teamMemberId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.Work.WebApi.TeamMemberCapacityIdentityRef>> GetCapacitiesWithIdentityRefAsync(Microsoft.TeamFoundation.Core.WebApi.Types.TeamContext teamContext, System.Guid iterationId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetCapacitiesWithIdentityRefAsync(teamContext, iterationId, userState, cancellationToken);
        public Uri BaseAddress
           => Client.BaseAddress;
        public bool ExcludeUrlsHeader
        {
           get => Client.ExcludeUrlsHeader;
           set => Client.ExcludeUrlsHeader = value;
        }
        public Microsoft.VisualStudio.Services.WebApi.VssResponseContext LastResponseContext
           => Client.LastResponseContext;
        public bool LightweightHeader
        {
           get => Client.LightweightHeader;
           set => Client.LightweightHeader = value;
        }
        public bool IsDisposed()
           => Client.IsDisposed();
        public void SetResourceLocations(Microsoft.VisualStudio.Services.WebApi.ApiResourceLocationCollection resourceLocations)
           => Client.SetResourceLocations(resourceLocations);
        public void Dispose()
	        => Client.Dispose();
   }
}