//HintName: TfsCmdlets.HttpClients.IWorkItemTrackingProcessHttpClient.g.cs
#pragma warning disable CS8669
using System.Composition;
using Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi;
namespace TfsCmdlets.HttpClients
{
    public partial interface IWorkItemTrackingProcessHttpClient: Microsoft.VisualStudio.Services.WebApi.IVssHttpClient
    {
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehavior> CreateProcessBehaviorAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehaviorCreateRequest behavior, System.Guid processId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeleteProcessBehaviorAsync(System.Guid processId, string behaviorRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehavior> GetProcessBehaviorAsync(System.Guid processId, string behaviorRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehavior>> GetProcessBehaviorsAsync(System.Guid processId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehavior> UpdateProcessBehaviorAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehaviorUpdateRequest behaviorData, System.Guid processId, string behaviorRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control> CreateControlInGroupAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control control, System.Guid processId, string witRefName, string groupId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control> MoveControlToGroupAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control control, System.Guid processId, string witRefName, string groupId, string controlId, string removeFromGroupId = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task RemoveControlFromGroupAsync(System.Guid processId, string witRefName, string groupId, string controlId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control> UpdateControlAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control control, System.Guid processId, string witRefName, string groupId, string controlId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField> AddFieldToWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.AddProcessWorkItemTypeFieldRequest field, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField>> GetAllWorkItemTypeFieldsAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField> GetWorkItemTypeFieldAsync(System.Guid processId, string witRefName, string fieldRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeFieldsExpandLevel? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeFieldsExpandLevel?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task RemoveWorkItemTypeFieldAsync(System.Guid processId, string witRefName, string fieldRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField> UpdateWorkItemTypeFieldAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.UpdateProcessWorkItemTypeFieldRequest field, System.Guid processId, string witRefName, string fieldRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group> AddGroupAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group group, System.Guid processId, string witRefName, string pageId, string sectionId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group> MoveGroupToPageAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group group, System.Guid processId, string witRefName, string pageId, string sectionId, string groupId, string removeFromPageId, string removeFromSectionId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group> MoveGroupToSectionAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group group, System.Guid processId, string witRefName, string pageId, string sectionId, string groupId, string removeFromSectionId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task RemoveGroupAsync(System.Guid processId, string witRefName, string pageId, string sectionId, string groupId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group> UpdateGroupAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group group, System.Guid processId, string witRefName, string pageId, string sectionId, string groupId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FormLayout> GetFormLayoutAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList> CreateListAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList picklist, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeleteListAsync(System.Guid listId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList> GetListAsync(System.Guid listId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickListMetadata>> GetListsMetadataAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList> UpdateListAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList picklist, System.Guid listId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Page> AddPageAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Page page, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task RemovePageAsync(System.Guid processId, string witRefName, string pageId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Page> UpdatePageAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Page page, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessInfo> CreateNewProcessAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.CreateProcessModel createRequest, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeleteProcessByIdAsync(System.Guid processTypeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessInfo> EditProcessAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.UpdateProcessModel updateRequest, System.Guid processTypeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessInfo>> GetListOfProcessesAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetProcessExpandLevel? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetProcessExpandLevel?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessInfo> GetProcessByItsIdAsync(System.Guid processTypeId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetProcessExpandLevel? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetProcessExpandLevel?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessRule> AddProcessWorkItemTypeRuleAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.CreateProcessRuleRequest processRuleCreate, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeleteProcessWorkItemTypeRuleAsync(System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessRule> GetProcessWorkItemTypeRuleAsync(System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessRule>> GetProcessWorkItemTypeRulesAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessRule> UpdateProcessWorkItemTypeRuleAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.UpdateProcessRuleRequest processRule, System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel> CreateStateDefinitionAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateInputModel stateModel, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeleteStateDefinitionAsync(System.Guid processId, string witRefName, System.Guid stateId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel> GetStateDefinitionAsync(System.Guid processId, string witRefName, System.Guid stateId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel>> GetStateDefinitionsAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel> HideStateDefinitionAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.HideStateModel hideStateModel, System.Guid processId, string witRefName, System.Guid stateId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel> UpdateStateDefinitionAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateInputModel stateModel, System.Guid processId, string witRefName, System.Guid stateId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control[]> DeleteSystemControlAsync(System.Guid processId, string witRefName, string controlId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control[]> GetSystemControlsAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control> UpdateSystemControlAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control control, System.Guid processId, string witRefName, string controlId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemType> CreateProcessWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.CreateProcessWorkItemTypeRequest workItemType, System.Guid processId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeleteProcessWorkItemTypeAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemType> GetProcessWorkItemTypeAsync(System.Guid processId, string witRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemType>> GetProcessWorkItemTypesAsync(System.Guid processId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemType> UpdateProcessWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.UpdateProcessWorkItemTypeRequest workItemTypeUpdate, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior> AddBehaviorToWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior behavior, System.Guid processId, string witRefNameForBehaviors, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior> GetBehaviorForWorkItemTypeAsync(System.Guid processId, string witRefNameForBehaviors, string behaviorRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior>> GetBehaviorsForWorkItemTypeAsync(System.Guid processId, string witRefNameForBehaviors, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task RemoveBehaviorFromWorkItemTypeAsync(System.Guid processId, string witRefNameForBehaviors, string behaviorRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior> UpdateBehaviorToWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior behavior, System.Guid processId, string witRefNameForBehaviors, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeModel> GetWorkItemTypeAsync(System.Guid processId, string witRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeModel>> GetWorkItemTypesAsync(System.Guid processId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemBehavior> GetBehaviorAsync(System.Guid processId, string behaviorRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemBehavior>> GetBehaviorsAsync(System.Guid processId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel> AddWorkItemTypeRuleAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel fieldRule, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task DeleteWorkItemTypeRuleAsync(System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel> GetWorkItemTypeRuleAsync(System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel>> GetWorkItemTypeRulesAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel> UpdateWorkItemTypeRuleAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel fieldRule, System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldModel>> GetFieldsAsync(System.Guid processId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldModel>> GetWorkItemTypeFieldsAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField> GetWorkItemTypeFieldAsync(System.Guid processId, string witRefName, string fieldRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
    [Export(typeof(IWorkItemTrackingProcessHttpClient))]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal class IWorkItemTrackingProcessHttpClientImpl: IWorkItemTrackingProcessHttpClient
    {
        private Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.WorkItemTrackingProcessHttpClient _client;
        protected IDataManager Data { get; }
        [ImportingConstructor]
        public IWorkItemTrackingProcessHttpClientImpl(IDataManager data)
        {
            Data = data;
        }
        private Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.WorkItemTrackingProcessHttpClient Client
        {
            get
            {
                if(_client == null)
                {
                    _client = (Data.GetCollection() as TfsCmdlets.Services.ITfsServiceProvider)?.GetClient(typeof(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.WorkItemTrackingProcessHttpClient)) as Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.WorkItemTrackingProcessHttpClient;
                }
                return _client;
            }
        }
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehavior> CreateProcessBehaviorAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehaviorCreateRequest behavior, System.Guid processId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateProcessBehaviorAsync(behavior, processId, userState, cancellationToken);
		public System.Threading.Tasks.Task DeleteProcessBehaviorAsync(System.Guid processId, string behaviorRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteProcessBehaviorAsync(processId, behaviorRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehavior> GetProcessBehaviorAsync(System.Guid processId, string behaviorRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetProcessBehaviorAsync(processId, behaviorRefName, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehavior>> GetProcessBehaviorsAsync(System.Guid processId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetProcessBehaviorsAsync(processId, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehavior> UpdateProcessBehaviorAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessBehaviorUpdateRequest behaviorData, System.Guid processId, string behaviorRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateProcessBehaviorAsync(behaviorData, processId, behaviorRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control> CreateControlInGroupAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control control, System.Guid processId, string witRefName, string groupId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateControlInGroupAsync(control, processId, witRefName, groupId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control> MoveControlToGroupAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control control, System.Guid processId, string witRefName, string groupId, string controlId, string removeFromGroupId = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.MoveControlToGroupAsync(control, processId, witRefName, groupId, controlId, removeFromGroupId, userState, cancellationToken);
		public System.Threading.Tasks.Task RemoveControlFromGroupAsync(System.Guid processId, string witRefName, string groupId, string controlId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.RemoveControlFromGroupAsync(processId, witRefName, groupId, controlId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control> UpdateControlAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control control, System.Guid processId, string witRefName, string groupId, string controlId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateControlAsync(control, processId, witRefName, groupId, controlId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField> AddFieldToWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.AddProcessWorkItemTypeFieldRequest field, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.AddFieldToWorkItemTypeAsync(field, processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField>> GetAllWorkItemTypeFieldsAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetAllWorkItemTypeFieldsAsync(processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField> GetWorkItemTypeFieldAsync(System.Guid processId, string witRefName, string fieldRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeFieldsExpandLevel? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeFieldsExpandLevel?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetWorkItemTypeFieldAsync(processId, witRefName, fieldRefName, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task RemoveWorkItemTypeFieldAsync(System.Guid processId, string witRefName, string fieldRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.RemoveWorkItemTypeFieldAsync(processId, witRefName, fieldRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField> UpdateWorkItemTypeFieldAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.UpdateProcessWorkItemTypeFieldRequest field, System.Guid processId, string witRefName, string fieldRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateWorkItemTypeFieldAsync(field, processId, witRefName, fieldRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group> AddGroupAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group group, System.Guid processId, string witRefName, string pageId, string sectionId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.AddGroupAsync(group, processId, witRefName, pageId, sectionId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group> MoveGroupToPageAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group group, System.Guid processId, string witRefName, string pageId, string sectionId, string groupId, string removeFromPageId, string removeFromSectionId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.MoveGroupToPageAsync(group, processId, witRefName, pageId, sectionId, groupId, removeFromPageId, removeFromSectionId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group> MoveGroupToSectionAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group group, System.Guid processId, string witRefName, string pageId, string sectionId, string groupId, string removeFromSectionId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.MoveGroupToSectionAsync(group, processId, witRefName, pageId, sectionId, groupId, removeFromSectionId, userState, cancellationToken);
		public System.Threading.Tasks.Task RemoveGroupAsync(System.Guid processId, string witRefName, string pageId, string sectionId, string groupId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.RemoveGroupAsync(processId, witRefName, pageId, sectionId, groupId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group> UpdateGroupAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Group group, System.Guid processId, string witRefName, string pageId, string sectionId, string groupId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateGroupAsync(group, processId, witRefName, pageId, sectionId, groupId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FormLayout> GetFormLayoutAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetFormLayoutAsync(processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList> CreateListAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList picklist, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateListAsync(picklist, userState, cancellationToken);
		public System.Threading.Tasks.Task DeleteListAsync(System.Guid listId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteListAsync(listId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList> GetListAsync(System.Guid listId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetListAsync(listId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickListMetadata>> GetListsMetadataAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetListsMetadataAsync(userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList> UpdateListAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.PickList picklist, System.Guid listId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateListAsync(picklist, listId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Page> AddPageAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Page page, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.AddPageAsync(page, processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task RemovePageAsync(System.Guid processId, string witRefName, string pageId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.RemovePageAsync(processId, witRefName, pageId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Page> UpdatePageAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Page page, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdatePageAsync(page, processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessInfo> CreateNewProcessAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.CreateProcessModel createRequest, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateNewProcessAsync(createRequest, userState, cancellationToken);
		public System.Threading.Tasks.Task DeleteProcessByIdAsync(System.Guid processTypeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteProcessByIdAsync(processTypeId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessInfo> EditProcessAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.UpdateProcessModel updateRequest, System.Guid processTypeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.EditProcessAsync(updateRequest, processTypeId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessInfo>> GetListOfProcessesAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetProcessExpandLevel? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetProcessExpandLevel?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetListOfProcessesAsync(expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessInfo> GetProcessByItsIdAsync(System.Guid processTypeId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetProcessExpandLevel? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetProcessExpandLevel?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetProcessByItsIdAsync(processTypeId, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessRule> AddProcessWorkItemTypeRuleAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.CreateProcessRuleRequest processRuleCreate, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.AddProcessWorkItemTypeRuleAsync(processRuleCreate, processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task DeleteProcessWorkItemTypeRuleAsync(System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteProcessWorkItemTypeRuleAsync(processId, witRefName, ruleId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessRule> GetProcessWorkItemTypeRuleAsync(System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetProcessWorkItemTypeRuleAsync(processId, witRefName, ruleId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessRule>> GetProcessWorkItemTypeRulesAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetProcessWorkItemTypeRulesAsync(processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessRule> UpdateProcessWorkItemTypeRuleAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.UpdateProcessRuleRequest processRule, System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateProcessWorkItemTypeRuleAsync(processRule, processId, witRefName, ruleId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel> CreateStateDefinitionAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateInputModel stateModel, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateStateDefinitionAsync(stateModel, processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task DeleteStateDefinitionAsync(System.Guid processId, string witRefName, System.Guid stateId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteStateDefinitionAsync(processId, witRefName, stateId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel> GetStateDefinitionAsync(System.Guid processId, string witRefName, System.Guid stateId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetStateDefinitionAsync(processId, witRefName, stateId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel>> GetStateDefinitionsAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetStateDefinitionsAsync(processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel> HideStateDefinitionAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.HideStateModel hideStateModel, System.Guid processId, string witRefName, System.Guid stateId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.HideStateDefinitionAsync(hideStateModel, processId, witRefName, stateId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateResultModel> UpdateStateDefinitionAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemStateInputModel stateModel, System.Guid processId, string witRefName, System.Guid stateId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateStateDefinitionAsync(stateModel, processId, witRefName, stateId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control[]> DeleteSystemControlAsync(System.Guid processId, string witRefName, string controlId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteSystemControlAsync(processId, witRefName, controlId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control[]> GetSystemControlsAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetSystemControlsAsync(processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control> UpdateSystemControlAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.Control control, System.Guid processId, string witRefName, string controlId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateSystemControlAsync(control, processId, witRefName, controlId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemType> CreateProcessWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.CreateProcessWorkItemTypeRequest workItemType, System.Guid processId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateProcessWorkItemTypeAsync(workItemType, processId, userState, cancellationToken);
		public System.Threading.Tasks.Task DeleteProcessWorkItemTypeAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteProcessWorkItemTypeAsync(processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemType> GetProcessWorkItemTypeAsync(System.Guid processId, string witRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetProcessWorkItemTypeAsync(processId, witRefName, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemType>> GetProcessWorkItemTypesAsync(System.Guid processId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetProcessWorkItemTypesAsync(processId, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemType> UpdateProcessWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.UpdateProcessWorkItemTypeRequest workItemTypeUpdate, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateProcessWorkItemTypeAsync(workItemTypeUpdate, processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior> AddBehaviorToWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior behavior, System.Guid processId, string witRefNameForBehaviors, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.AddBehaviorToWorkItemTypeAsync(behavior, processId, witRefNameForBehaviors, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior> GetBehaviorForWorkItemTypeAsync(System.Guid processId, string witRefNameForBehaviors, string behaviorRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBehaviorForWorkItemTypeAsync(processId, witRefNameForBehaviors, behaviorRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior>> GetBehaviorsForWorkItemTypeAsync(System.Guid processId, string witRefNameForBehaviors, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBehaviorsForWorkItemTypeAsync(processId, witRefNameForBehaviors, userState, cancellationToken);
		public System.Threading.Tasks.Task RemoveBehaviorFromWorkItemTypeAsync(System.Guid processId, string witRefNameForBehaviors, string behaviorRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.RemoveBehaviorFromWorkItemTypeAsync(processId, witRefNameForBehaviors, behaviorRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior> UpdateBehaviorToWorkItemTypeAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeBehavior behavior, System.Guid processId, string witRefNameForBehaviors, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateBehaviorToWorkItemTypeAsync(behavior, processId, witRefNameForBehaviors, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeModel> GetWorkItemTypeAsync(System.Guid processId, string witRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetWorkItemTypeAsync(processId, witRefName, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemTypeModel>> GetWorkItemTypesAsync(System.Guid processId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetWorkItemTypeExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetWorkItemTypesAsync(processId, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemBehavior> GetBehaviorAsync(System.Guid processId, string behaviorRefName, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBehaviorAsync(processId, behaviorRefName, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.WorkItemBehavior>> GetBehaviorsAsync(System.Guid processId, Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand? expand = default(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetBehaviorsExpand?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetBehaviorsAsync(processId, expand, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel> AddWorkItemTypeRuleAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel fieldRule, System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.AddWorkItemTypeRuleAsync(fieldRule, processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task DeleteWorkItemTypeRuleAsync(System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteWorkItemTypeRuleAsync(processId, witRefName, ruleId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel> GetWorkItemTypeRuleAsync(System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetWorkItemTypeRuleAsync(processId, witRefName, ruleId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel>> GetWorkItemTypeRulesAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetWorkItemTypeRulesAsync(processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel> UpdateWorkItemTypeRuleAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldRuleModel fieldRule, System.Guid processId, string witRefName, System.Guid ruleId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateWorkItemTypeRuleAsync(fieldRule, processId, witRefName, ruleId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldModel>> GetFieldsAsync(System.Guid processId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetFieldsAsync(processId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.List<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.FieldModel>> GetWorkItemTypeFieldsAsync(System.Guid processId, string witRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetWorkItemTypeFieldsAsync(processId, witRefName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.ProcessWorkItemTypeField> GetWorkItemTypeFieldAsync(System.Guid processId, string witRefName, string fieldRefName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetWorkItemTypeFieldAsync(processId, witRefName, fieldRefName, userState, cancellationToken);
        public Uri BaseAddress
           => Client.BaseAddress;
        public bool ExcludeUrlsHeader
        {
           get => Client.ExcludeUrlsHeader;
           set => Client.ExcludeUrlsHeader = value;
        }
        public Microsoft.VisualStudio.Services.WebApi.VssResponseContext LastResponseContext
           => Client.LastResponseContext;
        public bool LightweightHeader
        {
           get => Client.LightweightHeader;
           set => Client.LightweightHeader = value;
        }
        public bool IsDisposed()
           => Client.IsDisposed();
        public void SetResourceLocations(Microsoft.VisualStudio.Services.WebApi.ApiResourceLocationCollection resourceLocations)
           => Client.SetResourceLocations(resourceLocations);
        public void Dispose()
	        => Client.Dispose();
   }
}