//HintName: TfsCmdlets.HttpClients.IIdentityHttpClient.g.cs
using System.Composition;
using Microsoft.VisualStudio.Services.Identity.Client;
namespace TfsCmdlets.HttpClients
{
    public partial interface IIdentityHttpClient: Microsoft.VisualStudio.Services.WebApi.IVssHttpClient
    {
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.IdentityDescriptor> descriptors, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.IdentityDescriptor> descriptors, Microsoft.VisualStudio.Services.Identity.RequestHeadersContext requestHeadersContext, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Common.SocialDescriptor> socialDescriptors, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Common.SubjectDescriptor> subjectDescriptors, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<System.Guid> identityIds, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(Microsoft.VisualStudio.Services.Identity.IdentitySearchFilter searchFilter, string filterValue, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(Microsoft.VisualStudio.Services.Identity.IdentitySearchFilter searchFilter, string filterValue, Microsoft.VisualStudio.Services.Identity.ReadIdentitiesOptions options, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Guid scopeId, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.Identity> ReadIdentityAsync(string identityPuid, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.Identity> ReadIdentityAsync(System.Guid identityId, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Services.Identity.IdentityUpdateData>> UpdateIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.Identity> identities, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Services.Identity.IdentityUpdateData>> UpdateIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.Identity> identities, bool allowMetaDataUpdate, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> UpdateIdentityAsync(Microsoft.VisualStudio.Services.Identity.Identity identity, object userState, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> SwapIdentityAsync(System.Guid id1, System.Guid id2, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.ChangedIdentities> GetIdentityChangesAsync(int identitySequenceId, int groupSequenceId, System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.ChangedIdentities> GetIdentityChangesAsync(int identitySequenceId, int groupSequenceId, int organizationIdentitySequenceId, System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.ChangedIdentities> GetIdentityChangesAsync(int identitySequenceId, int groupSequenceId, int organizationIdentitySequenceId, int pageSize, System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Collections.Generic.IList<System.Guid>> GetUserIdentityIdsByDomainIdAsync(System.Guid domainId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitySelf> GetIdentitySelfAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.TenantInfo> GetTenant(string tenantId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.Identity> CreateFrameworkIdentityAsync(Microsoft.VisualStudio.Services.Identity.FrameworkIdentityType identityType, string role, string identifier, string displayName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ListGroupsAsync(System.Guid[] scopeIds = null, bool recurse = false, bool deleted = false, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> DeleteGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor descriptor, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> DeleteGroupAsync(System.Guid groupId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> CreateGroupsAsync(System.Guid scopeId, System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.Identity> groups, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentityScope> GetScopeAsync(string scopeName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentityScope> GetScopeAsync(System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentityScope> CreateScopeAsync(System.Guid scopeId, System.Guid parentScopeId, Microsoft.VisualStudio.Services.Identity.GroupScopeType scopeType, string scopeName, string adminGroupName, string adminGroupDescription, System.Guid creatorId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> RenameScopeAsync(System.Guid scopeId, string newName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> DeleteScopeAsync(System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> RestoreGroupScopeAsync(System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<bool> AddMemberToGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, System.Guid memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<bool> AddMemberToGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, Microsoft.VisualStudio.Services.Identity.IdentityDescriptor memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<bool> RemoveMemberFromGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, Microsoft.VisualStudio.Services.Identity.IdentityDescriptor memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<bool> ForceRemoveMemberFromGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, Microsoft.VisualStudio.Services.Identity.IdentityDescriptor memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<bool> IsMember(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, Microsoft.VisualStudio.Services.Identity.IdentityDescriptor memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitySnapshot> GetIdentitySnapshotAsync(System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.DelegatedAuthorization.AccessTokenResult> GetSignoutToken(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.DelegatedAuthorization.AccessTokenResult> GetSignedInToken(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<int> GetMaxSequenceIdAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.Identity> CreateOrBindIdentity(Microsoft.VisualStudio.Services.Identity.Identity sourceIdentity, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentityDescriptor> GetDescriptorByIdAsync(System.Guid id, bool? isMasterId = default(bool?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task TransferIdentityRightsBatchAsync(Microsoft.VisualStudio.Services.Identity.IdentityRightsTransferData identityRightsTransferData, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task TransferIdentityRightsSingleAsync(System.Guid sourceId, System.Guid targetMasterId, System.Guid sourceMasterId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.PagedIdentities> ListUsersAsync(string scopeDescriptor = null, string continuationToken = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
		public System.Threading.Tasks.Task<bool> AddMemberToGroupAsyncInternal(object routeParams, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, string>> query, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
    [Export(typeof(IIdentityHttpClient))]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal class IIdentityHttpClientImpl: IIdentityHttpClient
    {
        private Microsoft.VisualStudio.Services.Identity.Client.IdentityHttpClient _client;
        protected IDataManager Data { get; }
        [ImportingConstructor]
        public IIdentityHttpClientImpl(IDataManager data)
        {
            Data = data;
        }
        private Microsoft.VisualStudio.Services.Identity.Client.IdentityHttpClient Client
        {
            get
            {
                if(_client == null)
                {
                    _client = (Data.GetCollection() as TfsCmdlets.Services.ITfsServiceProvider)?.GetClient(typeof(Microsoft.VisualStudio.Services.Identity.Client.IdentityHttpClient)) as Microsoft.VisualStudio.Services.Identity.Client.IdentityHttpClient;
                }
                return _client;
            }
        }
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentitiesAsync(queryMembership, propertyNameFilters, includeRestrictedVisibility, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.IdentityDescriptor> descriptors, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentitiesAsync(descriptors, queryMembership, propertyNameFilters, includeRestrictedVisibility, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.IdentityDescriptor> descriptors, Microsoft.VisualStudio.Services.Identity.RequestHeadersContext requestHeadersContext, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentitiesAsync(descriptors, requestHeadersContext, queryMembership, propertyNameFilters, includeRestrictedVisibility, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Common.SocialDescriptor> socialDescriptors, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentitiesAsync(socialDescriptors, queryMembership, propertyNameFilters, includeRestrictedVisibility, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Common.SubjectDescriptor> subjectDescriptors, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentitiesAsync(subjectDescriptors, queryMembership, propertyNameFilters, includeRestrictedVisibility, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Collections.Generic.IList<System.Guid> identityIds, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, bool includeRestrictedVisibility = false, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentitiesAsync(identityIds, queryMembership, propertyNameFilters, includeRestrictedVisibility, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(Microsoft.VisualStudio.Services.Identity.IdentitySearchFilter searchFilter, string filterValue, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentitiesAsync(searchFilter, filterValue, queryMembership, propertyNameFilters, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(Microsoft.VisualStudio.Services.Identity.IdentitySearchFilter searchFilter, string filterValue, Microsoft.VisualStudio.Services.Identity.ReadIdentitiesOptions options, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentitiesAsync(searchFilter, filterValue, options, queryMembership, propertyNameFilters, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ReadIdentitiesAsync(System.Guid scopeId, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentitiesAsync(scopeId, queryMembership, propertyNameFilters, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.Identity> ReadIdentityAsync(string identityPuid, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentityAsync(identityPuid, queryMembership, propertyNameFilters, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.Identity> ReadIdentityAsync(System.Guid identityId, Microsoft.VisualStudio.Services.Identity.QueryMembership queryMembership = 0, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ReadIdentityAsync(identityId, queryMembership, propertyNameFilters, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Services.Identity.IdentityUpdateData>> UpdateIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.Identity> identities, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateIdentitiesAsync(identities, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Services.Identity.IdentityUpdateData>> UpdateIdentitiesAsync(System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.Identity> identities, bool allowMetaDataUpdate, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateIdentitiesAsync(identities, allowMetaDataUpdate, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> UpdateIdentityAsync(Microsoft.VisualStudio.Services.Identity.Identity identity, object userState, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.UpdateIdentityAsync(identity, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> SwapIdentityAsync(System.Guid id1, System.Guid id2, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.SwapIdentityAsync(id1, id2, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.ChangedIdentities> GetIdentityChangesAsync(int identitySequenceId, int groupSequenceId, System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetIdentityChangesAsync(identitySequenceId, groupSequenceId, scopeId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.ChangedIdentities> GetIdentityChangesAsync(int identitySequenceId, int groupSequenceId, int organizationIdentitySequenceId, System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetIdentityChangesAsync(identitySequenceId, groupSequenceId, organizationIdentitySequenceId, scopeId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.ChangedIdentities> GetIdentityChangesAsync(int identitySequenceId, int groupSequenceId, int organizationIdentitySequenceId, int pageSize, System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetIdentityChangesAsync(identitySequenceId, groupSequenceId, organizationIdentitySequenceId, pageSize, scopeId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Collections.Generic.IList<System.Guid>> GetUserIdentityIdsByDomainIdAsync(System.Guid domainId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetUserIdentityIdsByDomainIdAsync(domainId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitySelf> GetIdentitySelfAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetIdentitySelfAsync(userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.TenantInfo> GetTenant(string tenantId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetTenant(tenantId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.Identity> CreateFrameworkIdentityAsync(Microsoft.VisualStudio.Services.Identity.FrameworkIdentityType identityType, string role, string identifier, string displayName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateFrameworkIdentityAsync(identityType, role, identifier, displayName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> ListGroupsAsync(System.Guid[] scopeIds = null, bool recurse = false, bool deleted = false, System.Collections.Generic.IEnumerable<string> propertyNameFilters = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ListGroupsAsync(scopeIds, recurse, deleted, propertyNameFilters, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> DeleteGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor descriptor, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteGroupAsync(descriptor, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> DeleteGroupAsync(System.Guid groupId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteGroupAsync(groupId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitiesCollection> CreateGroupsAsync(System.Guid scopeId, System.Collections.Generic.IList<Microsoft.VisualStudio.Services.Identity.Identity> groups, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateGroupsAsync(scopeId, groups, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentityScope> GetScopeAsync(string scopeName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetScopeAsync(scopeName, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentityScope> GetScopeAsync(System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetScopeAsync(scopeId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentityScope> CreateScopeAsync(System.Guid scopeId, System.Guid parentScopeId, Microsoft.VisualStudio.Services.Identity.GroupScopeType scopeType, string scopeName, string adminGroupName, string adminGroupDescription, System.Guid creatorId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateScopeAsync(scopeId, parentScopeId, scopeType, scopeName, adminGroupName, adminGroupDescription, creatorId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> RenameScopeAsync(System.Guid scopeId, string newName, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.RenameScopeAsync(scopeId, newName, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> DeleteScopeAsync(System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.DeleteScopeAsync(scopeId, userState, cancellationToken);
		public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> RestoreGroupScopeAsync(System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.RestoreGroupScopeAsync(scopeId, userState, cancellationToken);
		public System.Threading.Tasks.Task<bool> AddMemberToGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, System.Guid memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.AddMemberToGroupAsync(containerId, memberId, userState, cancellationToken);
		public System.Threading.Tasks.Task<bool> AddMemberToGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, Microsoft.VisualStudio.Services.Identity.IdentityDescriptor memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.AddMemberToGroupAsync(containerId, memberId, userState, cancellationToken);
		public System.Threading.Tasks.Task<bool> RemoveMemberFromGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, Microsoft.VisualStudio.Services.Identity.IdentityDescriptor memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.RemoveMemberFromGroupAsync(containerId, memberId, userState, cancellationToken);
		public System.Threading.Tasks.Task<bool> ForceRemoveMemberFromGroupAsync(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, Microsoft.VisualStudio.Services.Identity.IdentityDescriptor memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ForceRemoveMemberFromGroupAsync(containerId, memberId, userState, cancellationToken);
		public System.Threading.Tasks.Task<bool> IsMember(Microsoft.VisualStudio.Services.Identity.IdentityDescriptor containerId, Microsoft.VisualStudio.Services.Identity.IdentityDescriptor memberId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.IsMember(containerId, memberId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentitySnapshot> GetIdentitySnapshotAsync(System.Guid scopeId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetIdentitySnapshotAsync(scopeId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.DelegatedAuthorization.AccessTokenResult> GetSignoutToken(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetSignoutToken(userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.DelegatedAuthorization.AccessTokenResult> GetSignedInToken(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetSignedInToken(userState, cancellationToken);
		public System.Threading.Tasks.Task<int> GetMaxSequenceIdAsync(object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetMaxSequenceIdAsync(userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.Identity> CreateOrBindIdentity(Microsoft.VisualStudio.Services.Identity.Identity sourceIdentity, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.CreateOrBindIdentity(sourceIdentity, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.IdentityDescriptor> GetDescriptorByIdAsync(System.Guid id, bool? isMasterId = default(bool?), object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.GetDescriptorByIdAsync(id, isMasterId, userState, cancellationToken);
		public System.Threading.Tasks.Task TransferIdentityRightsBatchAsync(Microsoft.VisualStudio.Services.Identity.IdentityRightsTransferData identityRightsTransferData, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.TransferIdentityRightsBatchAsync(identityRightsTransferData, userState, cancellationToken);
		public System.Threading.Tasks.Task TransferIdentityRightsSingleAsync(System.Guid sourceId, System.Guid targetMasterId, System.Guid sourceMasterId, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.TransferIdentityRightsSingleAsync(sourceId, targetMasterId, sourceMasterId, userState, cancellationToken);
		public System.Threading.Tasks.Task<Microsoft.VisualStudio.Services.Identity.PagedIdentities> ListUsersAsync(string scopeDescriptor = null, string continuationToken = null, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.ListUsersAsync(scopeDescriptor, continuationToken, userState, cancellationToken);
		public System.Threading.Tasks.Task<bool> AddMemberToGroupAsyncInternal(object routeParams, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, string>> query, object userState = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
			=> Client.AddMemberToGroupAsyncInternal(routeParams, query, userState, cancellationToken);
        public Uri BaseAddress
           => Client.BaseAddress;
        public bool ExcludeUrlsHeader
        {
           get => Client.ExcludeUrlsHeader;
           set => Client.ExcludeUrlsHeader = value;
        }
        public Microsoft.VisualStudio.Services.WebApi.VssResponseContext LastResponseContext
           => Client.LastResponseContext;
        public bool LightweightHeader
        {
           get => Client.LightweightHeader;
           set => Client.LightweightHeader = value;
        }
        public bool IsDisposed()
           => Client.IsDisposed();
        public void SetResourceLocations(Microsoft.VisualStudio.Services.WebApi.ApiResourceLocationCollection resourceLocations)
           => Client.SetResourceLocations(resourceLocations);
        public void Dispose()
	        => Client.Dispose();
   }
}