/*
.SYNOPSIS
Detaches a team project collection database from a Team Foundation Server installation

.DESCRIPTION
Before you move a collection, you must first detach it from the deployment of TFS on which it is running. It"s very important that you not skip this step. When you detach a collection, all jobs and services are stopped, and then the collection database is stopped. In addition, the detach process copies over the collection-specific data from the configuration database and saves it as part of the team project collection database. This configuration data is what allows the collection database to be attached to a different deployment of TFS. If that data is not present, you cannot attach the collection to any deployment of TFS except the one from which it originated.
If detachment succeeds, the original database connection string is returned. It is required to re-attach the collection to TFS.

.PARAMETER Reason
Speficies a Servicing Message (optional), to provide a message for users who might try to connect to projects in this collection

.PARAMETER Timeout
The maximum period of time this cmdlet should wait for the detach procedure to complete. By default, it waits indefinitely until the collection servicing completes

.PARAMETER Collection
Specifies either a URL/name of the Team Project Collection to connect to, or a previously initialized TfsTeamProjectCollection object. 

When using a URL, it must be fully qualified. The format of this string is as follows: 

http[s]://<ComputerName>:<Port>/[<TFS-vDir>/]<CollectionName> 

Valid values for the Transport segment of the URI are HTTP and HTTPS. If you specify a connection URI with a Transport segment, but do not specify a port, the session is created with standards ports: 80 for HTTP and 443 for HTTPS. 

To connect to a Team Project Collection by using its name, a TfsConfigurationServer object must be supplied either via -Server argument or via a previous call to the Connect-TfsConfigurationServer cmdlet. 

For more details, see the Get-TfsTeamProjectCollection cmdlet.

.PARAMETER Server
Specifies either a URL/name of the Team Foundation Server to connect to, or a previously initialized TfsConfigurationServer object. 

When using a URL, it must be fully qualified. The format of this string is as follows: 

http[s]://<ComputerName>:<Port>/[<TFS-vDir>/] 

Valid values for the Transport segment of the URI are HTTP and HTTPS. If you specify a connection URI with a Transport segment, but do not specify a port, the session is created with standards ports: 80 for HTTP and 443 for HTTPS.nnTo connect to a Team Foundation Server instance by using its name, it must have been previously registered.

.PARAMETER Credential
Specifies a user account that has permission to perform this action. The default is the credential of the user under which the PowerShell process is being run - in most cases that corresponds to the user currently logged in.nnType a user name, such as "User01" or "Domain01\User01", or enter a PSCredential object, such as one generated by the Get-Credential cmdlet. If you type a user name, you will be prompted for a password.nnTo connect to Visual Studio Team Services you must either: enable Alternate Credentials for your user profile and supply that credential in this argument or omit this argument to have a logon being dialog displayed automatically.nnFor more information on Alternate Credentials for your Visual Studio Team Services account, please refer to https://msdn.microsoft.com/library/dd286572#setup_basic_auth.

.INPUTS
Microsoft.TeamFoundation.Client.TfsConfigurationServer
System.String
System.Uri

.EXAMPLE
Dismount-TfsTeamProjectCollection -Collection http://vsalm:8080/tfs/DefaultCollection -Reason "Collection DefaultCollecton is down for maintenance"
Detaches the project collection specified by the URL provided in the Collection argument, defining a Maintenance Message to be shown to users when they try to connect to that collection while it is detached

.LINK
https://www.visualstudio.com/en-us/docs/setup-admin/tfs/admin/move-project-collection#1-detach-the-collection

.NOTES
Detaching a collection prevents users from accessing any projects in that collection
*/

using System.Management.Automation;

namespace TfsCmdlets.Cmdlets.TeamProjectCollection
{
    [Cmdlet(VerbsData.Dismount, "TeamProjectCollection", ConfirmImpact = ConfirmImpact.High, SupportsShouldProcess=true)]
	[OutputType(typeof(string))]
    public class DismountTeamProjectCollection: BaseCmdlet
    {
/*
		[Parameter(Mandatory=true, Position=0)]
        public object Collection,

		[Parameter(ValueFromPipeline=true)]
        public object Server,
	
		[Parameter()]
		public string Reason { get; set; }
	
		[Parameter()]
		public timespan Timeout { get; set; } = timespan.MaxValue,

		[Parameter()]
		public object Credential { get; set; }

	protected override void ProcessRecord()
	{
		tpc = Get-TfsTeamProjectCollection -Collection Collection -Server Server -Credential Credential

		if (ShouldProcess(tpc.Name, "Detach Project Collection"))
		{
			configServer = tpc.ConfigurationServer
			tpcService = configServer.GetService([type] "Microsoft.TeamFoundation.Framework.Client.ITeamProjectCollectionService")
			collectionInfo = tpcService.GetCollection(tpc.InstanceId)
			connectionString = null

			tpcJob = tpcService.QueueDetachCollection(collectionInfo, null, Reason, [ref] connectionString)
			collectionInfo = tpcService.WaitForCollectionServicingToComplete(tpcJob, Timeout)

			WriteObject(connectionString); return;
		}
	}
}
*/
    protected override void EndProcessing() => throw new System.NotImplementedException();
    }
}
