#define HELP_PARAM_SERVER Specifies either a URL/name of the Team Foundation Server to connect to, or a previously initialized TfsConfigurationServer object. \
\
When using a URL, it must be fully qualified. The format of this string is as follows: \
\
http[s]://<ComputerName>:<Port>/[<TFS-vDir>/] \
\
Valid values for the Transport segment of the URI are HTTP and HTTPS. If you specify a connection URI with a Transport segment, but do not specify a port, the session is created with standards ports: 80 for HTTP and 443 for HTTPS.\n\nTo connect to a Team Foundation Server instance by using its name, it must have been previously registered.
#define HELP_PARAM_COLLECTION Specifies either a URL/name of the Team Project Collection to connect to, or a previously initialized TfsTeamProjectCollection object. \
\
When using a URL, it must be fully qualified. The format of this string is as follows: \
\
http[s]://<ComputerName>:<Port>/[<TFS-vDir>/]<CollectionName> \
\
Valid values for the Transport segment of the URI are HTTP and HTTPS. If you specify a connection URI with a Transport segment, but do not specify a port, the session is created with standards ports: 80 for HTTP and 443 for HTTPS. \
\
To connect to a Team Project Collection by using its name, a TfsConfigurationServer object must be supplied either via -Server argument or via a previous call to the Connect-TfsConfigurationServer cmdlet. \
\
For more details, see the Get-TfsTeamProjectCollection cmdlet.
#define HELP_PARAM_PROJECT Specifies either the name of the Team Project or a previously initialized Microsoft.TeamFoundation.WorkItemTracking.Client.Project object to connect to. If omitted, it defaults to the connection opened by Connect-TfsTeamProject (if any). \
\
For more details, see the Get-TfsTeamProject cmdlet.
#define HELP_PARAM_AREA Specifies the name, URI or path of an Area. Wildcards are permitted. If omitted, all Areas in the given Team Project are returned. \
To supply a path, use a backslash ('\\') between the path segments. Leading and trailing backslashes are optional. \
When supplying a URI, use URIs in the form of 'vstfs:///Classification/Node/<GUID>' (where <GUID> is the unique identifier of the given node)
#define HELP_PARAM_ITERATION Specifies the name, URI or path of an Iteration. Wildcards are permitted. If omitted, all Iterations in the given Team Project are returned.\n\nTo supply a path, use a backslash ('\\') between the path segments. Leading and trailing backslashes are optional.\n\nWhen supplying a URI, use URIs in the form of 'vstfs:///Classification/Node/<GUID>' (where <GUID> is the unique identifier of the given node).
#define HELP_PARAM_PASSTHRU Returns the results of the command. By default, this cmdlet does not generate any output. 
#define HELP_PARAM_TFSCREDENTIAL Specifies a user account that has permission to perform this action. The default is the cached credential of the user under which the PowerShell process is being run - in most cases that corresponds to the user currently logged in. To provide a user name and password, and/or to open a input dialog to enter your credentials, call Get-TfsCredential with the appropriate arguments and pass its return to this argument. For more information, refer to https://msdn.microsoft.com/en-us/library/microsoft.teamfoundation.client.tfsclientcredentials.aspx
#define HELP_PARAM_CREDENTIAL Specifies a user account that has permission to perform this action. The default is the credential of the user under which the PowerShell process is being run - in most cases that corresponds to the user currently logged in.\n\nType a user name, such as 'User01' or 'Domain01\\User01', or enter a PSCredential object, such as one generated by the Get-Credential cmdlet. If you type a user name, you will be prompted for a password.\n\nTo connect to Visual Studio Team Services you must either: enable Alternate Credentials for your user profile and supply that credential in this argument or omit this argument to have a logon being dialog displayed automatically.\n\nFor more information on Alternate Credentials for your Visual Studio Team Services account, please refer to https://msdn.microsoft.com/library/dd286572#setup_basic_auth.
#define HELP_PARAM_INTERACTIVE Prompts for user credentials. Can be used for any Azure DevOps account - the proper login dialog is automatically selected. Should only be used in an interactive PowerShell session (i.e., a PowerShell terminal window), never in an unattended script (such as those executed during an automated build).